name: blackgate
# include:
# - ../blockchain-local-setup/docker-compose.yml
services:
  frontend:
    build:
      context: ../frontend
    ports:
      - "10000:80"
    env_file:
      - ${ENV_FILE}
    profiles:
      - deploy
    depends_on:
      - connector
    

  connector:
    build:
      context: ../connector
    # environment:
    # - PYTHONPATH=/app
    ports:
      - "10001:10000"
    env_file:
      - ${ENV_FILE}
    depends_on:
      - credential-server
      - grafana
    # volumes:
    # - ../connector:/app
    # command: ls -la /app
    profiles:
      - deploy
    

  credential-server:
    build:
      context: ../credential-issuer
    ports:
      - "10002:3000"
    env_file:
      - ${ENV_FILE}
    depends_on:
      - zksync
    profiles:
      - deploy
    

  reth:
    extends:
      file: ../blockchain-local-setup/docker-compose.yml
      service: reth
    profiles: ["blockchain", "deploy"]

  postgres:
    extends:
      file: ../blockchain-local-setup/docker-compose.yml
      service: postgres
    profiles: ["blockchain", "deploy"]

  zksync:
    extends:
      file: ../blockchain-local-setup/docker-compose.yml
      service: zksync
    ports:
      - "10005:3000"
    profiles: ["blockchain", "deploy"]

  # GRAFANA WOKRS FINE
  grafana:
    image: grafana/grafana:latest
    ports:
      - "10004:3000"
    volumes:
      - ../grafana/files/${DEPLOY_ENV}/grafana.ini:/etc/grafana/grafana.ini
      - ../grafana/files/${DEPLOY_ENV}/grafana.db:/var/lib/grafana/grafana.db
    depends_on:
      - zksync
    profiles:
      - deploy
    

