# WARNING::
# Failed to setup dynamic var loading for frontend
# Any and all Variables for frontend have to be defined in 
# docker.compose.yml | .env.example | dockerfile
# WARNING::

name: blackgate
# include:
# - ../blockchain-local-setup/docker-compose.yml
services:
  # frontend:
  #   build:
  #     context: ../frontend
  #   ports:
  #     - "10000:5173"
  #   env_file:
  #     - ${ENV_FILE}
  #   profiles:
  #     - deploy
  #   depends_on:
  #     - connector
  #   networks:
  #     - blackgate-network
  frontend:
    extends:
      file: ../frontend/docker-compose.yml
      service: frontend
    profiles: ["frontend", "deploy"]
    networks:
      - blackgate-network

  connector:
    build:
      context: ../connector
    # environment:
    # - PYTHONPATH=/app
    ports:
      - "10001:10001"
    env_file:
      - ${ENV_FILE}
    depends_on:
      - credential-server
      - grafana
    # volumes:
    # - ../connector:/app
    # command: ls -la /app
    profiles: ["deploy", "connector"]
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    networks:
      - blackgate-network
    

  credential-server:
    build:
      context: ../credential-issuer
    ports:
      - "10002:5000"
    env_file:
      - ${ENV_FILE}
    # depends_on:
      # - zksync
    profiles: ["deploy", "credential-server", "connector"]
    networks:
      - blackgate-network
    

  reth:
    extends:
      file: ../blockchain-local-setup/docker-compose.yml
      service: reth
    profiles: ["blockchain", "deploy"]
    networks:
      - blackgate-network

  postgres:
    extends:
      file: ../blockchain-local-setup/docker-compose.yml
      service: postgres
    profiles: ["blockchain", "deploy"]
    networks:
      - blackgate-network

  zksync:
    extends:
      file: ../blockchain-local-setup/docker-compose.yml
      service: zksync
    ports:
      - "10005:3000"
    profiles: ["blockchain", "deploy"]
    networks:
      - blackgate-network

  # GRAFANA WOKRS FINE
  grafana:
    image: grafana/grafana:latest
    ports:
      - "10004:3000"
    volumes:
      - ../grafana/files/${DEPLOY_ENV}/grafana.ini:/etc/grafana/grafana.ini
      - ../grafana/files/${DEPLOY_ENV}/grafana.db:/var/lib/grafana/grafana.db
    # depends_on:
      # - zksync
    profiles: ["deploy", "grafana", "connector"]
    networks:
      - blackgate-network
    

networks:
  blackgate-network:
    driver: bridge
  frontend-network:
    driver: bridge